/// Excel Generator Service
/// 
/// Service untuk generate laporan dalam format Excel (.xlsx).

library;

import 'package:excel/excel.dart';
import 'package:intl/intl.dart';

import '../../models/offspring.dart';
import '../../models/finance.dart';

class ExcelGenerator {
  static final _currencyFormat = NumberFormat('#,###', 'id');
  static final _dateFormat = DateFormat('dd MMM yyyy', 'id');

  /// Generate Sales Report Excel
  static List<int> generateSalesReport({
    required String farmName,
    required List<Offspring> soldOffsprings,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    final excel = Excel.createExcel();
    final sheet = excel['Laporan Penjualan'];

    // Delete default sheet
    excel.delete('Sheet1');

    // Styling
    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.fromHexString('#4CAF50'),
      fontColorHex: ExcelColor.white,
      horizontalAlign: HorizontalAlign.Center,
    );

    final titleStyle = CellStyle(
      bold: true,
      fontSize: 14,
    );

    // Title
    sheet.cell(CellIndex.indexByString('A1')).value = TextCellValue('Laporan Penjualan - $farmName');
    sheet.cell(CellIndex.indexByString('A1')).cellStyle = titleStyle;
    sheet.merge(CellIndex.indexByString('A1'), CellIndex.indexByString('E1'));

    // Date range
    sheet.cell(CellIndex.indexByString('A2')).value = TextCellValue(
      'Periode: ${_dateFormat.format(startDate)} - ${_dateFormat.format(endDate)}',
    );
    sheet.merge(CellIndex.indexByString('A2'), CellIndex.indexByString('E2'));

    // Empty row
    // Row 3 is empty

    // Summary
    final totalCount = soldOffsprings.length;
    final totalRevenue = soldOffsprings.fold(0.0, (sum, o) => sum + (o.salePrice ?? 0));

    sheet.cell(CellIndex.indexByString('A4')).value = TextCellValue('Total Terjual:');
    sheet.cell(CellIndex.indexByString('B4')).value = TextCellValue('$totalCount ekor');
    sheet.cell(CellIndex.indexByString('D4')).value = TextCellValue('Total Pendapatan:');
    sheet.cell(CellIndex.indexByString('E4')).value = TextCellValue('Rp ${_currencyFormat.format(totalRevenue)}');

    // Headers (row 6)
    final headers = ['No', 'Kode', 'Gender', 'Tanggal Jual', 'Harga'];
    for (int i = 0; i < headers.length; i++) {
      final cell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 5));
      cell.value = TextCellValue(headers[i]);
      cell.cellStyle = headerStyle;
    }

    // Data rows
    for (int i = 0; i < soldOffsprings.length; i++) {
      final o = soldOffsprings[i];
      final row = i + 6; // Starting from row 7 (index 6)

      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row)).value = 
          IntCellValue(i + 1);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row)).value = 
          TextCellValue(o.code);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row)).value = 
          TextCellValue(o.gender.value == 'male' ? 'Jantan' : 'Betina');
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row)).value = 
          TextCellValue(o.saleDate != null ? _dateFormat.format(o.saleDate!) : '-');
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 4, rowIndex: row)).value = 
          TextCellValue('Rp ${_currencyFormat.format(o.salePrice ?? 0)}');
    }

    // Set column widths
    sheet.setColumnWidth(0, 8);  // No
    sheet.setColumnWidth(1, 25); // Kode
    sheet.setColumnWidth(2, 12); // Gender
    sheet.setColumnWidth(3, 18); // Tanggal
    sheet.setColumnWidth(4, 20); // Harga

    // Footer
    final footerRow = soldOffsprings.length + 8;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: footerRow)).value = 
        TextCellValue('Generated by DSFarm - ${_dateFormat.format(DateTime.now())}');

    return excel.encode()!;
  }

  /// Generate Finance Summary Excel
  static List<int> generateFinanceSummary({
    required String farmName,
    required List<FinanceTransaction> transactions,
    required Map<String, dynamic> summary,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    final excel = Excel.createExcel();
    final sheet = excel['Laporan Keuangan'];

    // Delete default sheet
    excel.delete('Sheet1');

    // Styling
    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.fromHexString('#2196F3'),
      fontColorHex: ExcelColor.white,
      horizontalAlign: HorizontalAlign.Center,
    );

    final incomeStyle = CellStyle(
      fontColorHex: ExcelColor.fromHexString('#4CAF50'),
    );

    final expenseStyle = CellStyle(
      fontColorHex: ExcelColor.fromHexString('#F44336'),
    );

    final titleStyle = CellStyle(
      bold: true,
      fontSize: 14,
    );

    // Title
    sheet.cell(CellIndex.indexByString('A1')).value = TextCellValue('Laporan Keuangan - $farmName');
    sheet.cell(CellIndex.indexByString('A1')).cellStyle = titleStyle;
    sheet.merge(CellIndex.indexByString('A1'), CellIndex.indexByString('D1'));

    // Date range
    sheet.cell(CellIndex.indexByString('A2')).value = TextCellValue(
      'Periode: ${_dateFormat.format(startDate)} - ${_dateFormat.format(endDate)}',
    );
    sheet.merge(CellIndex.indexByString('A2'), CellIndex.indexByString('D2'));

    // Summary
    final income = (summary['income'] as num?)?.toDouble() ?? 0;
    final expense = (summary['expense'] as num?)?.toDouble() ?? 0;
    final balance = income - expense;

    sheet.cell(CellIndex.indexByString('A4')).value = TextCellValue('Pemasukan:');
    sheet.cell(CellIndex.indexByString('B4')).value = TextCellValue('Rp ${_currencyFormat.format(income)}');
    sheet.cell(CellIndex.indexByString('B4')).cellStyle = incomeStyle;

    sheet.cell(CellIndex.indexByString('C4')).value = TextCellValue('Pengeluaran:');
    sheet.cell(CellIndex.indexByString('D4')).value = TextCellValue('Rp ${_currencyFormat.format(expense)}');
    sheet.cell(CellIndex.indexByString('D4')).cellStyle = expenseStyle;

    sheet.cell(CellIndex.indexByString('A5')).value = TextCellValue('Saldo:');
    final balanceCell = sheet.cell(CellIndex.indexByString('B5'));
    balanceCell.value = TextCellValue('Rp ${_currencyFormat.format(balance)}');
    balanceCell.cellStyle = CellStyle(
      bold: true,
      fontColorHex: balance >= 0 
          ? ExcelColor.fromHexString('#4CAF50') 
          : ExcelColor.fromHexString('#F44336'),
    );

    // Headers (row 7)
    final headers = ['Tanggal', 'Kategori', 'Keterangan', 'Jumlah'];
    for (int i = 0; i < headers.length; i++) {
      final cell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 6));
      cell.value = TextCellValue(headers[i]);
      cell.cellStyle = headerStyle;
    }

    // Data rows
    for (int i = 0; i < transactions.length; i++) {
      final t = transactions[i];
      final row = i + 7;
      final isIncome = t.type == TransactionType.income;

      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row)).value = 
          TextCellValue(_dateFormat.format(t.transactionDate));
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row)).value = 
          TextCellValue(t.categoryName ?? '-');
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row)).value = 
          TextCellValue(t.description ?? '-');
      
      final amountCell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: row));
      amountCell.value = TextCellValue(
        '${isIncome ? '+' : '-'} Rp ${_currencyFormat.format(t.amount)}',
      );
      amountCell.cellStyle = isIncome ? incomeStyle : expenseStyle;
    }

    // Set column widths
    sheet.setColumnWidth(0, 18); // Tanggal
    sheet.setColumnWidth(1, 20); // Kategori
    sheet.setColumnWidth(2, 30); // Keterangan
    sheet.setColumnWidth(3, 20); // Jumlah

    // Footer
    final footerRow = transactions.length + 9;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: footerRow)).value = 
        TextCellValue('Generated by DSFarm - ${_dateFormat.format(DateTime.now())}');

    return excel.encode()!;
  }
}
